### ISSUE TITLE
hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [ddsjoberg/dcurves#12]
Hello ! 

I noticed this package has no hexagon logo, so i was wondering if you would be interested in using the one I created? The colors are from the header used on the website. The hexagon can be modified to your liking. 

I hope you like it, if so please Tweet me and let me know @StarTrek_Lt , Zane Dax. Thanks
![DCA hex](https://user-images.githubusercontent.com/55933131/174658794-80dd39d3-be6c-4b57-8444-b46d73e6e4d7.png)

**Comment by ddsjoberg** [comment]
Wow, thanks Zane! It looks so cool!

My husband is a graphic designer and he made a hex already. But I haven't had time to upload it yet. I need to get on it!
