### ISSUE TITLE
How to create a decision curve with multiple models?

### ISSUE THREAD

**Issue by hhchang0210** [ddsjoberg/dcurves#2]
Hi,
This is a great tool for creating a decision curve. But I don't know how to create a decision curve plot with multiple prediction models? like this picture: 
![image](https://user-images.githubusercontent.com/42891908/120187198-183c3e80-c247-11eb-92fc-ae86bd15d01d.png)

I read the example which only demonstrates a single model.
Can anyone give a me hint? Thank you very much.

**Comment by ddsjoberg** [comment]
hi @hhchang0210 , thanks for the post!

The vignette has more examples in it, including how to include multiple predictions/models
http://www.danieldsjoberg.com/dcurves/articles/dca.html

```r
dca(cancer ~ famhistory + cancerpredmarker, 
    data = df_binary, 
    thresholds = seq(0, 0.35, by = 0.01)) %>%
  autoplot(smooth = TRUE)
#> Assuming '1' is [Event] and '0' is [non-Event]
```

![image](https://user-images.githubusercontent.com/26774684/120232892-828eb800-c222-11eb-8bbc-69f3e022b15f.png)


FYI, this project is still under development. I expect it to go to CRAN in June.
