### ISSUE TITLE
Interventions Avoided Question

### ISSUE THREAD

**Issue by alkat19** [ddsjoberg/dcurves#24]
Hey there and thank you for that excellent package.

I have a question regarding the interventions avoided computation. What formula is being used to compute it and what's the intuition behind it? Does it make use of the TNs and FNs or is it a comparison of net benefits across different strategies?

**Comment by ddsjoberg** [comment]
Hey hey @alkat19 ,

We have a dedicated page for questions about the DCA method. Bets to post there! Thanks

https://github.com/MSKCC-Epi-Bio/decisioncurveanalysis/discussions
